### ISSUE TITLE
Long videos (More than a few minutes)

### ISSUE THREAD

**Issue by TGSUB** [BiRabittoh/fixyoutube-go#1]
Hello dear
First of all, thank you for your good project
And I have a question for you, can I display large videos in Telegram by changing your code?
If possible, please tell me how
thank you

**Comment by birabittoh** [comment]
Hey there!

Unfortunately, Telegram's link preview system is not documented at all.

I did some extensive testing with various file sizes and found a hard limit at 20MB for video previews:

![tgFileSize](https://github.com/BiRabittoh/fixyoutube-go/assets/26506860/d8ed6a0e-f4d7-4556-8829-5ef8b7c5d4d2)

To better answer your question, you can try and display larger videos by changing the `MAX_SIZE_MB` environment variable (for example, in your `.env` file), but I'm afraid the Telegram crawler will refuse to display the video if its size exceeds the set limit of 20MBs.

**Comment by TGSUB** [comment]
Ok thank you
One of the best Telegram projects
Keep up the good work

**Comment by RoyRiv3r** [comment]
Hey there, what about youtube embed for discord (not short), it seems to only work for short video  
Not working : https://y.outube.duckdns.org/watch?v=RuVS7MsQk4Y
Working : https://y.outube.duckdns.org/watch?v=A01s-xbF3ZE
